import type { IncomingMessage, ServerResponse } from "node:http";

import { sendResponse } from "../httpServer.ts";
import { KnownError, validateHasJSONBody } from "../httpErrorHandler.ts";
import { AddAssetRelation, AddTaskRelation, GetProjectFromOpProjectId, GetTaskRelationsData } from "../data.ts";
import { CreateAssetRequest, GetGlobalKitsuClient } from "../kitsuClient.ts";
import { CreateUserStoryRequest, GetGlobalOPClient, type CreateUserStoryResponse } from "../openprojectClient.ts";

const ART_ASSET_WP_TYPE_ID = 8;

interface WorkPackageLike {
	id: unknown;
	subject: unknown;
	startDate: unknown;
	dueDate: unknown;
	description: unknown;
	_embedded: unknown;
	_links: unknown;
}

interface WorkPackageEmbeddedFieldsLike {
	project: unknown;
	type: unknown;
	priority: unknown;
	status: unknown;
}

function CheckWorkPackageLike(workPackage: unknown): workPackage is WorkPackageLike {
	return (
		typeof workPackage === "object" &&
		workPackage !== null &&
		"id" in workPackage &&
		"subject" in workPackage &&
		"_embedded" in workPackage &&
		"_links" in workPackage
	);
}

function CheckWorkPackageEmbeddedFieldsLike(embeddedFields: unknown): embeddedFields is WorkPackageEmbeddedFieldsLike {
	return (
		typeof embeddedFields === "object" &&
		embeddedFields !== null &&
		"project" in embeddedFields &&
		"type" in embeddedFields &&
		"priority" in embeddedFields &&
		"status" in embeddedFields
	);
}

export async function handleOpenProjectWebhook(
	request: IncomingMessage,
	response: ServerResponse<IncomingMessage>,
	_url: URL,
	_unhandledEndpoints: string[]
) {
	sendResponse(response, undefined, 200);

	// 1. Grab OP info
	// 2. Create Asset in Kitsu
	// 4. POST to data/entities/{id}/tasks
	// 5. Create each work package for each returned task created

	return ProcessOPWebhook(request, response)
		.then(async op_Data => {
			if (op_Data.project === undefined) throw new KnownError("No project found");

			const taskRelations = GetTaskRelationsData(op_Data.project);
			if (op_Data.op_WPTypeId !== taskRelations.OP_ART_ASSET_WP_TYPE_ID) throw new KnownError("Not an art asset");

			if (op_Data.op_action !== "work_package:created") throw new KnownError("Not a work_package:created action");

			const client = GetGlobalKitsuClient();
			return client.CreateAsset(
				op_Data.project,
				op_Data.op_AssetTypeId,
				new CreateAssetRequest(op_Data.op_Title, op_Data.op_Description ?? "")
			).then(kitsu_Data => ({ op_Data, kitsu_Data }));
		})
		.then(async ({ op_Data, kitsu_Data }) => {
			AddAssetRelation(op_Data.project!, op_Data.op_Id, kitsu_Data.id);

			const client = GetGlobalKitsuClient();
			return client.CreateTasks(kitsu_Data.id)
				.then(tasks_Data => ({ op_Data, kitsu_Data, tasks_Data }));
		})
		.then(async ({ op_Data, kitsu_Data, tasks_Data }) => {
			const client = GetGlobalOPClient();

			const responses: CreateUserStoryResponse[] = [];

			for (let i = 0; i < tasks_Data.length; i++) {
				const task = tasks_Data[i];

				await client.CreateUserStory(op_Data.project!, new CreateUserStoryRequest(`${op_Data.op_Title} - ${task.task_type_name}`, "Autogenerated from Kitsu", op_Data.op_Id))
					.then(userStory_Data => responses.push(userStory_Data));
			}

			return { op_Data, kitsu_Data, tasks_Data, userStories_Data: responses };
		})
		.then(({ op_Data, tasks_Data, userStories_Data }) => {
			for (let i = 0; i < tasks_Data.length; i++)
				AddTaskRelation(op_Data.project!, tasks_Data[i].id, userStories_Data[i].id);
		})
		.catch(error => {
			if (error instanceof KnownError) return;
			console.error(error);
		});
}

function sendInvalidWebhookResponse(response: ServerResponse<IncomingMessage>): never {
	sendResponse(response, undefined, 400);
	throw new KnownError("Invalid webhook");
}

async function ProcessOPWebhook(request: IncomingMessage, response: ServerResponse<IncomingMessage>) {
	const body = await validateHasJSONBody(request, response);

	if (typeof body !== "object" || body === null) sendInvalidWebhookResponse(response);
	if (!("action" in body) || !("work_package" in body)) sendInvalidWebhookResponse(response);
	if (typeof body.action !== "string" || body.action === null) sendInvalidWebhookResponse(response);

	const op_WorkPackage = body.work_package;
	if (typeof op_WorkPackage !== "object" || op_WorkPackage === null) sendInvalidWebhookResponse(response);
	if (!CheckWorkPackageLike(op_WorkPackage)) sendInvalidWebhookResponse(response);

	const op_WPId = op_WorkPackage.id;
	if (typeof op_WPId !== "number" || op_WPId === null) sendInvalidWebhookResponse(response);

	const op_Title = op_WorkPackage.subject;
	if (typeof op_Title !== "string" || op_Title === null) sendInvalidWebhookResponse(response);

	const op_EmbeddedFields = op_WorkPackage._embedded;
	if (!CheckWorkPackageEmbeddedFieldsLike(op_EmbeddedFields)) sendInvalidWebhookResponse(response);

	const op_ProjectFields = op_EmbeddedFields.project;
	if (typeof op_ProjectFields !== "object" || op_ProjectFields === null) sendInvalidWebhookResponse(response);
	if (!("id" in op_ProjectFields)) sendInvalidWebhookResponse(response);

	const op_ProjectId = op_ProjectFields.id;
	if (typeof op_ProjectId !== "number" || op_ProjectId === null) sendInvalidWebhookResponse(response);

	const op_WPType = op_EmbeddedFields.type;
	if (typeof op_WPType !== "object" || op_WPType === null) sendInvalidWebhookResponse(response);
	if (!("id" in op_WPType)) sendInvalidWebhookResponse(response);

	const op_WPTypeId = op_WPType.id;
	if (typeof op_WPTypeId !== "number" || op_WPTypeId === null) sendInvalidWebhookResponse(response);

	const op_WPStatus = op_EmbeddedFields.status;
	if (typeof op_WPStatus !== "object" || op_WPStatus === null) sendInvalidWebhookResponse(response);
	if (!("id" in op_WPStatus)) sendInvalidWebhookResponse(response);

	const op_WPStatusId = op_WPStatus.id;
	if (typeof op_WPStatusId !== "number" || op_WPStatusId === null) sendInvalidWebhookResponse(response);

	const op_LinksFields = op_WorkPackage._links;
	if (typeof op_LinksFields !== "object" || op_LinksFields === null) sendInvalidWebhookResponse(response);
	if (!("customField3" in op_LinksFields)) sendInvalidWebhookResponse(response);

	const op_AssetType = op_LinksFields.customField3;
	if (typeof op_AssetType !== "object" || op_AssetType === null) sendInvalidWebhookResponse(response);
	if (!("href" in op_AssetType)) sendInvalidWebhookResponse(response);

	const op_AssetTypeUrl = op_AssetType.href;
	if (typeof op_AssetTypeUrl !== "string" || op_AssetTypeUrl === null) sendInvalidWebhookResponse(response);

	const op_AssetTypeId = Number(/\d+$/.exec(op_AssetTypeUrl)?.[0]);
	if (isNaN(op_AssetTypeId)) sendInvalidWebhookResponse(response);

	// Optional fields, does not send invalid response if not present/misformatted
	// startDate, dueDate, priority, description->raw

	const startDateRaw = op_WorkPackage.startDate;
	const op_StartDate = typeof startDateRaw === "string" ? Temporal.PlainDateTime.from(startDateRaw) : undefined;

	const dueDateRaw = op_WorkPackage.dueDate;
	const op_DueDate = typeof dueDateRaw === "string" ? Temporal.PlainDateTime.from(dueDateRaw) : undefined;

	const descriptionObjectRaw = op_WorkPackage.description;
	const descriptionRaw =
		typeof descriptionObjectRaw === "object"
			&& descriptionObjectRaw !== null
			&& "raw" in descriptionObjectRaw
			? descriptionObjectRaw.raw
			: undefined;

	const op_Description = typeof descriptionRaw === "string" ? descriptionRaw : undefined;

	return {
		project: GetProjectFromOpProjectId(op_ProjectId),
		op_action: body.action,
		op_Id: op_WPId,
		op_Title,
		op_WPTypeId,
		op_WPStatusId,
		op_AssetTypeId,
		op_StartDate,
		op_EndDate: op_DueDate,
		op_Description
	};
}
